name: Unzip and Clean (Manual Trigger)

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许提交更改
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip 1/2/3.zip to n.phpx.cn/
        run: |
          mkdir -p n.phpx.cn
          unzip -o 1.zip -d n.phpx.cn/
          unzip -o 2.zip -d n.phpx.cn/
          unzip -o 3.zip -d n.phpx.cn/

      - name: Unzip a.zip to root
        run: unzip -o a.zip -d ./

      - name: Delete original ZIP files
        run: rm -f 1.zip 2.zip 3.zip a.zip

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto: Unzipped 1/2/3.zip to n.phpx.cn/, a.zip to root" || echo "No changes"
          git push
